### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by georgeedwards** [alexjoverm/Vue-Typescript-Starter#7]
I am new to vue, so this is probably a really stupid question, but I have done these steps:

1. `git clone https://github.com/alexjoverm/Vue-Typescript-Starter`
2. `cd Vue-Typescript-Starter`
3. `yarn install`
4. vue build src/main.ts --watch

and I get:

> ERROR in ./src/main.ts
Module not found: Error: Can't resolve './router' in 'C:\Users\George\Source\Repos\Vue-Typescript-Starter\src'
 @ ./src/main.ts 5:0-29
 @ multi src/main.ts

> ERROR in ./~/ts-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module build failed: Error: Could not find file: 'C:\Users\George\Source\Repos\Vue-Typescript-Starter\src\App.vue'.
    at getValidSourceFile (C:\Users\George\Source\Repos\Vue-Typescript-Starter\node_modules\typescript\lib\typescript.js:91389:23)
    at Object.getEmitOutput (C:\Users\George\Source\Repos\Vue-Typescript-Starter\node_modules\typescript\lib\typescript.js:91769:30)
    at getEmit (C:\Users\George\Source\Repos\Vue-Typescript-Starter\node_modules\ts-loader\dist\index.js:152:43)
    at successLoader (C:\Users\George\Source\Repos\Vue-Typescript-Starter\node_modules\ts-loader\dist\index.js:42:11)
    at Object.loader (C:\Users\George\Source\Repos\Vue-Typescript-Starter\node_modules\ts-loader\dist\index.js:29:12)
 @ ./src/App.vue 7:2-94
 @ ./src/main.ts
 @ multi src/main.ts

**Comment by FernandoBasso** [comment]
Run

```
npm run dev
```

from the root directory of the app. The directory that contains `package.json` and `README.md`.
